### ISSUE TITLE
[ADD WEBSITE]: https://www.hostloc.com/forum.php

### ISSUE THREAD

**Issue by 1tons** [FeedsPub/badge#10]
I am using Feeds Pub badge on my website

- Website URL:https://www.hostloc.com/forum-45-1.html
- Feed URL:https://www.hostloc.com/forum.php?mod=rss&fid=45&auth=a6bcIR5ml%2BFk4CgsygTWKxo1pM%2Byjws4q28FCcdeFPIVhCxh3RpnXOY15zzO8g

**Comment by timqian** [comment]
你好, 没有在这个网站上看到 feeds pub 的按钮呀

**Comment by 1tons** [comment]
你好，**美国VPS综合讨论** 这个板块右上角有个RSS

**Comment by timqian** [comment]
这里是用来加使用了 https://badge.feeds.pub 的网站的
