### ISSUE TITLE
[ADD WEBSITE]: Scvoet

### ISSUE THREAD

**Issue by scvoet** [FeedsPub/badge#11]
I am using Feeds Pub badge on my website

- Website URL: https://scvoet.me
- Feed URL: https://scvoet.me/feed

**Comment by timqian** [comment]
Thanks for using feeds.pub badge, I will add your blog to badge.feeds.pub soon~

**Comment by timqian** [comment]
Just updated https://badge.feeds.pub . Thanks again for supporting feeds.pub

**Comment by scvoet** [comment]
> Just updated https://badge.feeds.pub . Thanks again for supporting feeds.pub

![image](https://user-images.githubusercontent.com/45708948/96247115-3e74dd00-0fdc-11eb-9f1d-1d36a1ac393d.png)
What's wrong with it? Click on [About - Scvoet](https://scvoet.me/page/about) to review current status, please.

**Comment by timqian** [comment]
没问题哈, 我昨天已经把你的博客加到 https://badge.feeds.pub 上去啦
