### ISSUE TITLE
[ADD WEBSITE]: Fidel's Lab

### ISSUE THREAD

**Issue by Fidelxyz** [FeedsPub/badge#15]
I am using Feeds Pub badge on my website

- Website URL: https://fidel.js.org/
- Feed URL: https://fidel.js.org/rss.xml

**Comment by timqian** [comment]
Thanks, I will add the links to the website soon

**Comment by timqian** [comment]
Hi @Fidelxyz your website has been added to https://badge.feeds.pub thanks again for your support❤️
