### ISSUE TITLE
[ADD WEBSITE]: Panda Home

### ISSUE THREAD

**Issue by OldPanda** [feedspub/badge#5]
I am using Feeds Pub badge on my website

- Website URL: https://old-panda.com/
- Feed URL: https://old-panda.com/feed/

**Comment by timqian** [comment]
似乎没在网站上看到 badge 呀?

**Comment by timqian** [comment]
看到了, 感谢~ 也添加到了 https://badge.feeds.pub/

**Comment by OldPanda** [comment]
谢谢更新，希望越做越好！
